// GENERATED BY goruda
// This file was generated automatically at
// 2020-07-17 07:53:27.964749 +0700 WIB m=+0.011834117

package articletest

type Author struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
