// GENERATED BY goruda
// This file was generated automatically at
// 2020-07-17 07:53:27.959643 +0700 WIB m=+0.006727961

package articletest

type ChildOfArticle struct {
	Tag   `json:""`
	Topic `json:""`
}

func (p ChildOfArticle) ToTag() Tag {
	return p.Tag
}

func (p ChildOfArticle) ToTopic() Topic {
	return p.Topic
}
