// GENERATED BY goruda
// This file was generated automatically at
// 2020-07-17 07:53:27.965795 +0700 WIB m=+0.012880767

package articletest

type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type ErrorNotFound struct {
	Message string `json:"message"`
}

func (e ErrorNotFound) Error() string {
	return e.Message
}

type ErrorBadRequest struct {
	Message string `json:"message"`
}

func (e ErrorBadRequest) Error() string {
	return e.Message
}
