// GENERATED BY goruda
// This file was generated automatically at
// 0001-01-01 00:00:00 +0000 UTC

package articletest

type serviceImplementation struct {
	repo ArticleRepository
}

func (s serviceImplementation) Createarticles(article Article) (Article, error) {
	return s.repo.Createarticles(article)
}

func (s serviceImplementation) Deletearticlebyid(articleId string) error {
	return s.repo.Deletearticlebyid(articleId)
}

func (s serviceImplementation) Listarticles(num int32, cursor string) (Articles, string, error) {
	return s.repo.Listarticles(num, cursor)
}

func (s serviceImplementation) Showarticlebyid(articleId string) (Article, error) {
	return s.repo.Showarticlebyid(articleId)
}

func (s serviceImplementation) Updatearticle(articleId string, article Article) (Article, error) {
	return s.repo.Updatearticle(articleId, article)
}

func NewArticleService(repo ArticleRepository) ArticleService {
	return &serviceImplementation{
		repo: repo,
	}
}
