// GENERATED BY goruda
// This file was generated automatically at
// 2020-07-17 07:53:27.966497 +0700 WIB m=+0.013582285

package articletest

type Tag struct {
	Content ChildOfTag `json:"content"`
	Type    string     `json:"type"`
}
