// GENERATED BY goruda
// This file was generated automatically at
// 2020-07-17 07:53:27.968414 +0700 WIB m=+0.015499635

package articletest

type Topic struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
